# This file was generated by GoReleaser. DO NOT EDIT.
cask "wt" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "203ffea4999cbe86f86e47127539e0c1c11c70967e95335174608ed682442118"
      url "https://github.com/bklimov-web/wt-cli/releases/download/v#{version}/wt_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "bae51a96c36e5f8c66e37a1ae49e12eb2b525ab23df4924e33989e52b8692e37"
      url "https://github.com/bklimov-web/wt-cli/releases/download/v#{version}/wt_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f201b837f126202863e2274db6d1fc9173f66506a2b556ef08e0f976afd11f6e"
      url "https://github.com/bklimov-web/wt-cli/releases/download/v#{version}/wt_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "20d6be73685036c00f094af63357e7ba6f2782571ab390bda7fb18800d6c104c"
      url "https://github.com/bklimov-web/wt-cli/releases/download/v#{version}/wt_linux_amd64.tar.gz"
    end
  end

  name "wt"
  desc "Create git worktrees with local files and deps in place"
  homepage "https://github.com/bklimov-web/wt-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wt"

  # No zap stanza required
end
