# This file was generated by GoReleaser. DO NOT EDIT.
cask "wt" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "c91ad08de34f6aee2e33d8181a1285e7f096cc4c1c4659883778b4bc9263dc89"
      url "https://github.com/bklimov-web/wt-cli/releases/download/v#{version}/wt_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1fe0069d03c1208023b92448f1c9c93079b9812e1bbcfe0be1c9de20300bdc51"
      url "https://github.com/bklimov-web/wt-cli/releases/download/v#{version}/wt_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b33f2fe00130816048cd1e75088f1188b81de9070842ab6a46edf0fcbe64fe4f"
      url "https://github.com/bklimov-web/wt-cli/releases/download/v#{version}/wt_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "70e120c9904fbb1270e4f5574087fe5bb4c18b36f9ea14566fc1514d7a791fec"
      url "https://github.com/bklimov-web/wt-cli/releases/download/v#{version}/wt_linux_amd64.tar.gz"
    end
  end

  name "wt"
  desc "Create git worktrees with local files and deps in place"
  homepage "https://github.com/bklimov-web/wt-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wt"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wt"]
    end
  end

  # No zap stanza required
end
