# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wt < Formula
  desc "Create git worktrees with local files and deps in place"
  homepage "https://github.com/bklimov-web/wt-cli"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bklimov-web/wt-cli/releases/download/v0.1.3/wt_darwin_amd64.tar.gz"
      sha256 "ce7be0b64cd10624f66c5d1a98af974fc4322765d8bf620f356106d62d6a5b57"

      define_method(:install) do
        bin.install "wt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bklimov-web/wt-cli/releases/download/v0.1.3/wt_darwin_arm64.tar.gz"
      sha256 "db4a26121d4f8ff1106eed8cd8373acc2a0bf4875937e924f7298a7317bc91ad"

      define_method(:install) do
        bin.install "wt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bklimov-web/wt-cli/releases/download/v0.1.3/wt_linux_amd64.tar.gz"
      sha256 "47257e22fd1e851192170e1c0a26cd72669ae5917ea862e6a277cbe5fdc6cdb8"
      define_method(:install) do
        bin.install "wt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bklimov-web/wt-cli/releases/download/v0.1.3/wt_linux_arm64.tar.gz"
      sha256 "886c03e2f43495f4aac9de6152bbc3e100a6b79b91b4973cf228ec03c555eadc"
      define_method(:install) do
        bin.install "wt"
      end
    end
  end

  test do
    system "#{bin}/wt", "--help"
  end
end
