# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wt < Formula
  desc "Create git worktrees with local files and deps in place"
  homepage "https://github.com/bklimov-web/wt-cli"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bklimov-web/wt-cli/releases/download/v0.1.2/wt_darwin_amd64.tar.gz"
      sha256 "8cf34401220ab80653b23765ba48909fd825ac97dc32c0b5244744ae26ab7c94"

      define_method(:install) do
        bin.install "wt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bklimov-web/wt-cli/releases/download/v0.1.2/wt_darwin_arm64.tar.gz"
      sha256 "a1593d9ef05d0f4c747d3aecf18b34fbf03bd61ff849145ebcd31494b4d775e5"

      define_method(:install) do
        bin.install "wt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bklimov-web/wt-cli/releases/download/v0.1.2/wt_linux_amd64.tar.gz"
      sha256 "0971e1ef75dc65cd083f6a92fc71cf4d91049f3c8cc6f93bd05fc6680659cf3a"
      define_method(:install) do
        bin.install "wt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bklimov-web/wt-cli/releases/download/v0.1.2/wt_linux_arm64.tar.gz"
      sha256 "9fa1f41bf23eb693bfd172bfc408162cc78dd4d5833829e8d10738ca2bc0a007"
      define_method(:install) do
        bin.install "wt"
      end
    end
  end

  test do
    system "#{bin}/wt", "--help"
  end
end
